# Generated by Django 4.1.10 on 2023-07-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('pincode', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('is_fresher', models.BooleanField(default=True)),
                ('years_of_experience', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
